### ISSUE TITLE
Not compatible with 1.6.0 ElasticSearch version

### ISSUE THREAD

**Issue by leechuen** [jprante/elasticsearch-csv#11]
Hi,
I have been using this plugin and it works for ElasticSearch version 1.5.0.
After I upgrade ElasticSearch to version 1.6.0, I get this error when using this plugin:
{
   "error": "NoSuchMethodError[org.elasticsearch.rest.BytesRestResponse.<init>(Lorg/elasticsearch/rest/RestStatus;Ljava/lang/String;Lorg/elasticsearch/common/bytes/BytesReference;Z)V]",
   "status": 500
}

Are you planning to release a new version which is compatible with ES version 1.6.0?

In the logfile, it says:
[2015-07-15 03:51:09,755][ERROR][csv                      ] org.elasticsearch.rest.BytesRestResponse.<init>(Lorg/elasticsearch/rest/RestStatus;Ljava/lang/String;Lorg/elasticsearch/common/bytes/BytesReference;Z)V
java.lang.NoSuchMethodError: org.elasticsearch.rest.BytesRestResponse.<init>(Lorg/elasticsearch/rest/RestStatus;Ljava/lang/String;Lorg/elasticsearch/common/bytes/BytesReference;Z)V
	at org.xbib.elasticsearch.rest.csv.CSVToXContentListener.buildResponse(CSVToXContentListener.java:104)
	at org.xbib.elasticsearch.rest.csv.CSVToXContentListener.buildResponse(CSVToXContentListener.java:27)
	at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
	at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.doRun(TransportSearchQueryThenFetchAction.java:152)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by jprante** [comment]
Thanks for the report. I just released 1.6.0.0 version of CSV plugin.

**Comment by leechuen** [comment]
It works. Thanks.
