### ISSUE TITLE
Request Not Working with New Version of Elasticsearch

### ISSUE THREAD

**Issue by slcsecurity** [jprante/elasticsearch-csv#12]
This is all I get. The formats are good because it previously worked but I don't want to run a vulnerable version of elasticsearch as you know. I'm running 1.6.0 and the following output is all I get. 

{"error":"ElasticsearchIllegalArgumentException[No feature for name [_search_csv]]","status":400}

**Comment by jprante** [comment]
You did not install the plugin. Did you restart the node?

Check logs for a line like `loaded [csv-1.6.0.0-4bb5c38`

**Comment by slcsecurity** [comment]
No it's been restarted. 

Still getting this error. 

Here is the log snippet:
[2015-07-19 18:37:37,266][INFO ][plugins                  ] [Intel1] loaded [csv-1.6.0.0-4bb5c38], sites [kopf, head]

So it is loading. But since upgrading off of 1.4.4 of ES I can't get the plugin to work. 

Installed plugins:
    - csv
    - kopf
    - head


Let me know if you want access to the server to troubleshoot or need any additional information. I am more than willing to help figure it out as I use this feature and without it I'm dead in the water.

**Comment by jprante** [comment]
Can you describe the steps and the exact commands you execute until the error message appears?

**Comment by mattmarcello** [comment]
First of all, thanks for working on this.  It is much appreciated.

I am having a similar issue on es1.5. 

```bash 
curl -XGET 'http://localhost:9200/[INDEX]/_search_csv'
```

Yields the following response: 

```bash 
{"error":"NoSuchMethodError[org.elasticsearch.rest.BytesRestResponse.<init>(Lorg/elasticsearch/rest/RestStatus;Ljava/lang/String;Lorg/elasticsearch/common/bytes/BytesReference;)V]","status":500}%
```
Thanks and let me know if i can be of help.

**Comment by slcsecurity** [comment]
That's the exact same message I am getting. Basically using the same method (curl) to make request and the same thing happens when using a web browser. It worked great in 1.4 but after 1.5 this issue persist. 

I have uninstalled the plugin until we can figure it out. If need be I can reinstall it and test again but the previous author (mattmarcello) is describing exactly the response I see when I invoke the plugin.

**Comment by jprante** [comment]
Thanks for the comments. I just released plugin version 1.5.0.0 for Elasticsearch 1.5

**Comment by slcsecurity** [comment]
{"error":"NoSuchMethodError[org.elasticsearch.rest.BytesRestResponse.<init>(Lorg/elasticsearch/rest/RestStatus;Ljava/lang/String;Lorg/elasticsearch/common/bytes/BytesReference;Z)V]","status":500}

With 1.5.0.0

**Comment by slcsecurity** [comment]
Logged Errors:

[2015-08-16 21:01:53,864][ERROR][csv                      ] org.elasticsearch.rest.BytesRestResponse.<init>(Lorg/elasticsearch/rest/RestStatus;Ljava/lang/String;Lorg/elasticsearch/common/bytes/BytesReference;Z)V
java.lang.NoSuchMethodError: org.elasticsearch.rest.BytesRestResponse.<init>(Lorg/elasticsearch/rest/RestStatus;Ljava/lang/String;Lorg/elasticsearch/common/bytes/BytesReference;Z)V
        at org.xbib.elasticsearch.rest.csv.CSVToXContentListener.buildResponse(CSVToXContentListener.java:104)
        at org.xbib.elasticsearch.rest.csv.CSVToXContentListener.buildResponse(CSVToXContentListener.java:27)
        at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
        at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.doRun(TransportSearchQueryThenFetchAction.java:152)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by jprante** [comment]
```
[2015-08-17 10:22:18,894][INFO ][node                     ] [Fateball] version[1.5.0], pid[17758], build[5448160/2015-03-23T14:30:58Z]
[2015-08-17 10:22:18,895][INFO ][node                     ] [Fateball] initializing ...
[2015-08-17 10:22:19,174][INFO ][plugins                  ] [Fateball] loaded [csv-1.5.0.0-85df55e], sites []
```

```
curl -v '0:9200/_search_csv'
* Adding handle: conn: 0x7fea78803a00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fea78803a00) send_pipe: 1, recv_pipe: 0
* About to connect() to 0 port 9200 (#0)
*   Trying 0.0.0.0...
* Connected to 0 (0.0.0.0) port 9200 (#0)
> GET /_search_csv HTTP/1.1
> User-Agent: curl/7.30.0
> Host: 0:9200
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/csv
< Content-Length: 13323
< 
requestheaders.content-length,requestheaders.cookie,requestheaders.accept-language,requestheaders.origin,part.header.content-disposition,part.header.content-type,requestheaders.content-type,type,part.body,uri,requestheaders.accept-encoding,contenttype,requestheaders.cache-control,requestheaders.referer,path,part.length,requestheaders.host,part.header.name,part.header.filename,requestheaders.upgrade-insecure-requests,requestheaders.user-agent,requestheaders.connection,requestheaders.accept,timestamp
6134,SESSID=AU7-WD-XAuWOKOtN8moj_j5pwvZhKRl6wybU0mB2t6g,"de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4",http://localhost:9200,"form-data; name=""file2""; [...]
```

**Comment by jchan-scc** [comment]
Hi, I also get this error 
{
"error": "NoSuchMethodError[org.elasticsearch.rest.BytesRestResponse.<init>(Lorg/elasticsearch/rest/RestStatus;Ljava/lang/String;Lorg/elasticsearch/common/bytes/BytesReference;)V]",
"status": 500
}

**Comment by jprante** [comment]
Please use the correct version of the plugin.

**Comment by jchan-scc** [comment]
hi @jprante I'm using ./bin/plugin -install csv -url http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-csv/1.7.2.0/elasticsearch-csv-1.7.2.0-plugin.zip

**Comment by jprante** [comment]
See compatibility matrix, please use a version beginning with 1.4.x.y if you are on ES 1.4

**Comment by jchan-scc** [comment]
i see, thanks!
